name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set commit SHA
        id: commit_sha
        run: echo "::set-output name=SHA::$(git rev-parse --short ${{ github.sha }})"
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag dualping:${{ steps.commit_sha.outputs.SHA }}
